### ISSUE TITLE
Installing or building release tarball with Python 2.7 fails

### ISSUE THREAD

**Issue by epronk** [sassoftware/python-rpm-vercmp#1]
```
$ python setup.py build
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)

Installed /home/eddy/release/python-rpm-vercmp-0.1.0/.eggs/pbr-4.1.0-py2.7.egg
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/eddy/release/python-rpm-vercmp-0.1.0/.eggs/pbr-4.1.0-py2.7.egg/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/eddy/release/python-rpm-vercmp-0.1.0/.eggs/pbr-4.1.0-py2.7.egg/pbr/util.py", line 259, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/eddy/release/python-rpm-vercmp-0.1.0/.eggs/pbr-4.1.0-py2.7.egg/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/eddy/release/python-rpm-vercmp-0.1.0/.eggs/pbr-4.1.0-py2.7.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/eddy/release/python-rpm-vercmp-0.1.0/.eggs/pbr-4.1.0-py2.7.egg/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/eddy/release/python-rpm-vercmp-0.1.0/.eggs/pbr-4.1.0-py2.7.egg/pbr/packaging.py", line 824, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name rpm_vercmp was given, but was not able to be found.
error in setup command: Error parsing /home/eddy/release/python-rpm-vercmp-0.1.0/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name rpm_vercmp was given, but was not able to be found.

```

**Comment by wfscheper** [comment]
The error you got is a standard one from [pbr](https://docs.openstack.org/pbr/latest/index.html), and indicates that pbr was unable to determine the project version because of missing metadata.

Some ways to resolve the problem can be found in PBR's [documentation](https://docs.openstack.org/pbr/latest/user/packagers.html) or by using a full clone as follows:
```bash
$ python2.7 --version
Python 2.7.15
$ git clone https://github.com/sassoftware/python-rpm-vercmp.git
Cloning into 'python-rpm-vercmp'...
remote: Enumerating objects: 54, done.
remote: Total 54 (delta 0), reused 0 (delta 0), pack-reused 54
Receiving objects: 100% (54/54), 15.11 KiB | 3.78 MiB/s, done.
Resolving deltas: 100% (18/18), done.
$ cd python-rpm-vercmp/
$ python2.7 setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/rpm_vercmp
copying rpm_vercmp/__init__.py -> build/lib/rpm_vercmp
copying rpm_vercmp/vercmp.py -> build/lib/rpm_vercmp
creating build/lib/rpm_vercmp/tests
copying rpm_vercmp/tests/__init__.py -> build/lib/rpm_vercmp/tests
copying rpm_vercmp/tests/vercmp_test.py -> build/lib/rpm_vercmp/tests
running egg_info
creating rpm_vercmp.egg-info
writing pbr to rpm_vercmp.egg-info/pbr.json
writing rpm_vercmp.egg-info/PKG-INFO
writing top-level names to rpm_vercmp.egg-info/top_level.txt
writing dependency_links to rpm_vercmp.egg-info/dependency_links.txt
[pbr] Processing SOURCES.txt
writing manifest file 'rpm_vercmp.egg-info/SOURCES.txt'
[pbr] In git context, generating filelist from git
warning: no files found matching 'AUTHORS'
warning: no files found matching 'ChangeLog'
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.ico' under directory 'rpm_vercmp'
warning: no files found matching '*.png' under directory 'rpm_vercmp'
warning: no files found matching '*.css' under directory 'rpm_vercmp'
warning: no files found matching '*.gif' under directory 'rpm_vercmp'
warning: no files found matching '*.jpg' under directory 'rpm_vercmp'
warning: no files found matching '*.pt' under directory 'rpm_vercmp'
warning: no files found matching '*.txt' under directory 'rpm_vercmp'
warning: no files found matching '*.mak' under directory 'rpm_vercmp'
warning: no files found matching '*.mako' under directory 'rpm_vercmp'
warning: no files found matching '*.js' under directory 'rpm_vercmp'
warning: no files found matching '*.html' under directory 'rpm_vercmp'
warning: no files found matching '*.xml' under directory 'rpm_vercmp'
writing manifest file 'rpm_vercmp.egg-info/SOURCES.txt'
```
If that doesn't help, or you got the error from within a full clone, then re-open this issue and we'll see if we can work out how to reproduce it.
